### ISSUE TITLE
most important part of readme is missing

### ISSUE THREAD

**Issue by kargayerde** [ceeeKay/QESpeedometer#1]
you could've said how is it installed instead of redundantly stating "install like any other QE mod,"  probably using the same amount of keypresses.

**Comment by ceeeKay** [comment]
No I couldn't have because there are several ways you can set up the file for mods. Nevertheless I've added a line to the README for this 3 year-old repo.

Glad someone is still finding it interesting/useful, although the version in https://github.com/ceeeKay/QETweaks may be a bit nicer, as it got a few more improvements/fixes
